services:
  - docker

before_install:
- docker login ghcr.io -u marfgold1 -p $GHCR_PAT
- docker build -t marfgold1/arcwawan .
- docker tag marfgold1/arcwawan:latest ghcr.io/marfgold1/arcwawan:latest
- docker push ghcr.io/marfgold1/arcwawan:latest

scripts: 'true'
